import assert from 'node:assert/strict';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { MembershipSettings } from '../MembershipSettings.js';
import { PlayerDecklist } from '../PlayerDecklist.js';
import type { MembershipStatus } from '../types.js';
const status: MembershipStatus = { linked: false, email: null, plan: 'none', traceAccess: false, opponentDecklists: false, admin: false, status: 'unlinked', expiresAt: null, cancelAtPeriodEnd: false };
const render = (s: MembershipStatus) => renderToStaticMarkup(createElement(MembershipSettings, { status: s, onRefresh: async () => {}, onChange: () => {} }));
assert.match(render(status), /Link account/);
assert.match(render(status), /Trace Free/);
assert.match(render(status), /last 7 days of replays are free/);
assert.match(render(status), /1 new replay every 7 days/);
assert.match(render(status), /Older matches stay saved/);
assert.match(render(status), /before this upgrade stay available/);
assert.doesNotMatch(render(status), /to use Trace/);
assert.match(render({ ...status, status: 'unavailable' }), /Free features are ready/);
assert.doesNotMatch(render(status), /Manage membership|Owner access/);
const unavailable = render({ ...status, status: 'not_configured' });
assert.match(unavailable, /not available in this build/);
assert.doesNotMatch(unavailable, />Link account</);
const supporter = render({ ...status, linked: true, plan: 'supporter', traceAccess: true, opponentDecklists: true, status: 'active', capabilities: { recordMatches: true, leaderboard: true, recentReplayDays: 7, fullHistory: true, expandedSharing: true, opponentDecklists: true, freeSharesPerWindow: 1, shareWindowDays: 7 } });
assert.match(supporter, /Full replay history and unlimited sharing/);
assert.match(supporter, /Supporters Club/);
assert.match(supporter, /after the match result is recorded/);
assert.match(supporter, /Manage membership/);
assert.doesNotMatch(supporter, /Owner access/);
const locked = renderToStaticMarkup(createElement(PlayerDecklist, { name: 'Opponent', catalog: new Map(), unavailableReason: 'Available after Trace records the match result.' }));
assert.match(locked, /aria-disabled="true"/);
assert.match(locked, /after Trace records the match result/);
assert.doesNotMatch(locked, /Copy decklist|player-decklist-grid/);
const authorized = renderToStaticMarkup(createElement(PlayerDecklist, { name: 'Opponent', catalog: new Map(), loadDeck: async () => { throw new Error('not called until opening'); } }));
assert.match(authorized, /aria-disabled="false"/);
assert.doesNotMatch(authorized, /player-decklist-grid/);
console.log('membership-settings: account states, honest configuration status, after-match copy and fetch-on-open inventory verified');
