import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { SharedAccessRail } from '../SharedAccessRail.js';
import { readSharedAccessOpen, SHARED_ACCESS_KEY, storeSharedAccessOpen, TRACE_DISCORD_URL } from '../shared-access.js';

const values = new Map<string, string>();
const storage = { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => { values.set(key, value); } };
assert.equal(readSharedAccessOpen(storage, 1600), true);
assert.equal(readSharedAccessOpen(storage, 900), false);
storeSharedAccessOpen(storage, false);
assert.equal(readSharedAccessOpen(storage, 1600), false, 'Remember a collapsed invitation across shared matches');
storeSharedAccessOpen(storage, true);
assert.equal(readSharedAccessOpen(storage, 900), true, 'Honor an explicit choice on a narrower window');
values.set(SHARED_ACCESS_KEY, 'invalid');
assert.equal(readSharedAccessOpen(storage, 1600), true);
const unavailable = { getItem: () => { throw new Error('blocked'); }, setItem: () => { throw new Error('blocked'); } };
assert.equal(readSharedAccessOpen(unavailable, 1600), true);
assert.doesNotThrow(() => storeSharedAccessOpen(unavailable, false));
const render = (open: boolean) => renderToStaticMarkup(createElement(SharedAccessRail, { open, onToggle: () => {} }));
const expanded = render(true);
assert.match(expanded, /Want to record your games like this\?/);
assert.match(expanded, /Join the Discord/);
assert.match(expanded, /ask for <strong>Trace access/);
assert.match(expanded, /aria-expanded="true"/);
assert.match(expanded, /aria-controls="shared-access-content"/);
assert.ok(expanded.includes(`href="${TRACE_DISCORD_URL}"`));
assert.match(expanded, /target="_blank" rel="noopener noreferrer"/);
assert.match(expanded, /src="\/tracker-assets\/trace-mascot.png"/);
assert.match(expanded, /href="\/trace"/);
const collapsed = render(false);
assert.match(collapsed, /Expand Trace access panel/);
assert.match(collapsed, /aria-expanded="false"/);
assert.match(collapsed, /id="shared-access-content"[^>]*hidden=""/);
const app = readFileSync(new URL('../TrackerApp.tsx', import.meta.url), 'utf8');
assert.match(app, /sharedMode && <SharedAccessRail/);
assert.doesNotMatch(app, /shared-replay-header/);
assert.match(app, /!sharedMode && archiveOpen && <aside/);
console.log('shared-access: Discord invitation, real mascot, shared-only layout, collapse persistence and storage fallback passed');
