import fs from 'node:fs';
import { createHash } from 'node:crypto';

// Freeze the observed distribution so opening another page or playing a game
// cannot silently change historical icons. Refresh explicitly after reviewing the corpus.
const source = fs.readFileSync(new URL('../src/tracker/__tests__/fixtures/deck-identity-corpus.json', import.meta.url), 'utf8');
const corpus = JSON.parse(source);
const cards = new Map<string, { name: string; category: number }>(corpus.cards.map((c: any) => [c.id, c]));
const key = (s: string) => s.normalize('NFKC').replace(/[’‘]/g, "'").trim().toLowerCase();
const deckOccurrences = new Map<string, number>();
let deckCount = 0;
for (const deck of corpus.cases) {
  if (!Number.isInteger(deck.occurrences) || deck.occurrences < 1) throw new Error('Invalid deck occurrence count');
  const names = new Set<string>();
  for (const entry of deck.cards) {
    const card = cards.get(entry.cardId);
    if (!card) throw new Error(`Unresolved baseline card ${entry.cardId}`);
    if (card.category === 1) names.add(key(card.name));
  }
  deckCount += deck.occurrences;
  for (const name of names) deckOccurrences.set(name, (deckOccurrences.get(name) || 0) + deck.occurrences);
}
if (deckCount !== corpus.completeDeckSides) throw new Error('Baseline deck count does not match the reviewed corpus');
const baseline = { version: `local-${corpus.reviewedOn}`, sourceSha256: createHash('sha256').update(source).digest('hex'),
  deckCount, deckOccurrences: Object.fromEntries([...deckOccurrences].sort(([a], [b]) => a.localeCompare(b))) };
fs.writeFileSync(new URL('../src/tracker/deck-frequency-baseline.ts', import.meta.url),
  '// Generated by scripts/build-deck-frequency-baseline.ts from reviewed decklists.\n'
  + '// Counts are player-deck appearances, with cosmetic prints and copies counted once per deck.\n'
  + 'export const DECK_FREQUENCY_BASELINE = ' + JSON.stringify(baseline, null, 2) + ' as const;\n');
console.log(`Generated ${deckCount}-deck baseline for ${deckOccurrences.size} Pokémon names`);
